pim_enrich_group_type_index:
    path: /
    defaults: { _controller: pim_enrich.controller.group_type:indexAction }

pim_enrich_group_type_create:
    path: /create
    defaults: { _controller: pim_enrich.controller.group_type:createAction }

pim_enrich_group_type_edit:
    path: /{id}/edit
    defaults: { _controller: pim_enrich.controller.group_type:editAction }
    requirements:
        id: \d+

pim_enrich_group_type_remove:
    path: /{id}/remove
    defaults: { _controller: pim_enrich.controller.group_type:removeAction }
    requirements:
        id: \d+
    methods: [DELETE]
