config:
    shim:
        jquery.wizard:
            deps:
                - jquery
        jstree/jquery.jstree.tree_selector:
            deps:
                - jquery.jstree
        jstree/nested_switch:
            deps:
                - jquery.jstree

    config:
        pim/controller-registry:
            defaultController: pim/controller/template
            controllers:
                pim_enrich_association_type_edit:     pim/controller/form
                pim_enrich_attribute_edit:            pim/controller/form
                pim_enrich_attributegroup_create:     pim/controller/form
                pim_enrich_attributegroup_edit:       pim/controller/form
                pim_enrich_categorytree_create:       pim/controller/form
                pim_enrich_categorytree_edit:         pim/controller/form
                pim_enrich_channel_edit:              pim/controller/channel
                pim_enrich_family_edit:               pim/controller/form
                pim_enrich_group_edit:                pim/controller/form
                pim_enrich_group_type_edit:           pim/controller/form
                pim_enrich_product_edit:              pim/controller/form
                pim_enrich_variant_group_edit:        pim/controller/form
                pim_importexport_export_profile_edit: pim/controller/form
                pim_importexport_import_profile_edit: pim/controller/form
                oro_user_create:                      pim/controller/form
                oro_user_update:                      pim/controller/form
                oro_user_role_create:                 pim/controller/form
                oro_user_role_update:                 pim/controller/form
                oro_user_group_create:                pim/controller/form
                oro_user_group_update:                pim/controller/form

    paths:
        pim/app:                            pimenrich/js/app
        pim/router:                         pimenrich/js/router
        pim/route-matcher:                  pimenrich/js/route-matcher
        pim/page-title:                     pimenrich/js/page-title

        # Controllers
        pim/controller-registry:            pimenrich/js/controller/registry
        pim/controller/base:                pimenrich/js/controller/base
        pim/controller/template:            pimenrich/js/controller/template
        pim/controller/form:                pimenrich/js/controller/form
        pim/controller/channel:             pimenrich/js/controller/channel

        jquery.wizard:                      pimenrich/js/jquery.wizard
        jstree/jquery.jstree.tree_selector: pimenrich/js/jstree/jquery.jstree.tree_selector
        jstree/nested_switch:               pimenrich/js/jstree/jquery.jstree.nested_switch
        pim/init:                           pimenrich/js/pim-init
        pim/asynctab:                       pimenrich/js/pim-async-tab
        pim/popinform:                      pimenrich/js/pim-popinform
        pim/optionform:                     pimenrich/js/pim-optionform
        pim/scopable:                       pimenrich/js/pim-scopable
        pim/currencyfield:                  pimenrich/js/pim-currencyfield
        pim/tree/view:                      pimenrich/js/tree-view.jstree
        pim/tree/associate:                 pimenrich/js/tree-associate.jstree
        pim/tree/manage:                    pimenrich/js/tree-manage.jstree
        pim/attributeoptionview:            pimenrich/js/pim-attributeoptionview
        pim/item/tableview:                 pimenrich/js/pim-item-tableview
        pim/item/view:                      pimenrich/js/pim-item-view
